package rapid_evolution.ui;


public class ColumnConfig {
  static public int total_unique_columns = 53;

  public ColumnConfig() {
    num_columns = 0; columnindex = null; columntitles = null; preferredwidth = null;
    preferredWidths = new int[total_unique_columns];
    preferredWidths[0] = 350;
    preferredWidths[1] = 150;
    preferredWidths[2] = 150;
    preferredWidths[3] = 50;
    preferredWidths[4] = 150;
    preferredWidths[5] = 55;
    preferredWidths[6] = 65;
    preferredWidths[7] = 75;
    preferredWidths[8] = 75;
    preferredWidths[9] = 75;
    preferredWidths[10] = 75;
    preferredWidths[11] = 75;
    preferredWidths[12] = 75;
    preferredWidths[13] = 450;
    preferredWidths[14] = 1250;
    preferredWidths[15] = 50;
    preferredWidths[16] = 50;
    preferredWidths[17] = 50;
    preferredWidths[18] = 80;
    preferredWidths[19] = 70;
    preferredWidths[20] = 70;
    preferredWidths[21] = 500;
    preferredWidths[22] = 50;
    preferredWidths[23] = 65;
    preferredWidths[24] = 50;
    preferredWidths[25] = 75;
    preferredWidths[26] = 70;
    preferredWidths[27] = 150;
    preferredWidths[28] = 100;
    preferredWidths[29] = 100;
    preferredWidths[30] = 100;
    preferredWidths[31] = 100;
    preferredWidths[32] = 250;
    preferredWidths[33] = 400;
    preferredWidths[34] = 100;
    preferredWidths[35] = 70;
    preferredWidths[36] = 100;
    preferredWidths[37] = 110;
    preferredWidths[38] = 100;
    preferredWidths[39] = 300;
    preferredWidths[40] = 70;
    preferredWidths[41] = 100;
    preferredWidths[42] = 100;
    preferredWidths[43] = 200;
    preferredWidths[44] = 50;
    preferredWidths[45] = 110;
    preferredWidths[46] = 85;
    preferredWidths[47] = 75;
    preferredWidths[48] = 100;
    preferredWidths[49] = 75;
    preferredWidths[50] = 75;    
    preferredWidths[51] = 80;    
    preferredWidths[52] = 100;
  }
  private int[] preferredWidths;
  public void setDefaultWidth(int index, int val) {
      if (index >= 0)
          preferredWidths[index] = val;
  }
  public int getDefaultWidth(int i) { return preferredWidths[i]; }
  public void setIndex(int cindex) {
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_song_id"))) columnindex[cindex] = 0;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_artist"))) columnindex[cindex] = 1;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_album"))) columnindex[cindex] = 2;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_track"))) columnindex[cindex] = 3;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_title"))) columnindex[cindex] = 4;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_time"))) columnindex[cindex] = 5;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_time_signature"))) columnindex[cindex] = 6;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_bpm_start"))) columnindex[cindex] = 7;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_bpm_end"))) columnindex[cindex] = 8;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_bpm"))) columnindex[cindex] = 9;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_key_start"))) columnindex[cindex] = 10;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_key_end"))) columnindex[cindex] = 11;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_key"))) columnindex[cindex] = 12;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_song_comments"))) columnindex[cindex] = 13;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_filename"))) columnindex[cindex] = 14;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_analog"))) columnindex[cindex] = 15;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_digital"))) columnindex[cindex] = 16;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_disabled"))) columnindex[cindex] = 17;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_bpm_shift"))) columnindex[cindex] = 18;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_key_lock"))) columnindex[cindex] = 19;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_key_code"))) columnindex[cindex] = 35;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_num_mixouts"))) columnindex[cindex] = 20;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_song_id_with_info"))) columnindex[cindex] = 21;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_rank"))) columnindex[cindex] = 22;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_num_addons"))) columnindex[cindex] = 23;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_addon"))) columnindex[cindex] = 24;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_bpm_diff"))) columnindex[cindex] = 25;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_key_relation"))) columnindex[cindex] = 26;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_remix"))) columnindex[cindex] = 27;
    if (columntitles[cindex].equals(OptionsUI.instance.customfieldtext1.getText())) columnindex[cindex] = 28;
    if (columntitles[cindex].equals(OptionsUI.instance.customfieldtext2.getText())) columnindex[cindex] = 29;
    if (columntitles[cindex].equals(OptionsUI.instance.customfieldtext3.getText())) columnindex[cindex] = 30;
    if (columntitles[cindex].equals(OptionsUI.instance.customfieldtext4.getText())) columnindex[cindex] = 31;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_short_id"))) columnindex[cindex] = 32;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_short_id_with_info"))) columnindex[cindex] = 33;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_style_similarity"))) columnindex[cindex] = 34;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_color_similarity"))) columnindex[cindex] = 36;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_date_added"))) columnindex[cindex] = 37;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_artist_similarity"))) columnindex[cindex] = 38;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_mixout_comments"))) columnindex[cindex] = 39;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_num_plays"))) columnindex[cindex] = 40;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_key_accuracy"))) columnindex[cindex] = 41;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_bpm_accuracy"))) columnindex[cindex] = 42;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_styles"))) columnindex[cindex] = 43;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_has_album_cover"))) columnindex[cindex] = 44;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_last_modified"))) columnindex[cindex] = 45;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_rating"))) columnindex[cindex] = 46;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_actual_key"))) columnindex[cindex] = 47;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_pitch_shift"))) columnindex[cindex] = 48;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_actual_key_code"))) columnindex[cindex] = 49;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_beat_intensity"))) columnindex[cindex] = 50;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_replay_gain"))) columnindex[cindex] = 51;
    if (columntitles[cindex].equals(SkinManager.instance.getMessageText("column_title_album_cover"))) columnindex[cindex] = 52;
  }
  static public int getIndex(String title) {
    if (title.equals(SkinManager.instance.getMessageText("column_title_song_id"))) return 0;
    if (title.equals(SkinManager.instance.getMessageText("column_title_artist"))) return 1;
    if (title.equals(SkinManager.instance.getMessageText("column_title_album"))) return 2;
    if (title.equals(SkinManager.instance.getMessageText("column_title_track"))) return 3;
    if (title.equals(SkinManager.instance.getMessageText("column_title_title"))) return 4;
    if (title.equals(SkinManager.instance.getMessageText("column_title_time"))) return 5;
    if (title.equals(SkinManager.instance.getMessageText("column_title_time_signature"))) return 6;
    if (title.equals(SkinManager.instance.getMessageText("column_title_bpm_start"))) return 7;
    if (title.equals(SkinManager.instance.getMessageText("column_title_bpm_end"))) return 8;
    if (title.equals(SkinManager.instance.getMessageText("column_title_bpm"))) return 9;
    if (title.equals(SkinManager.instance.getMessageText("column_title_key_start"))) return 10;
    if (title.equals(SkinManager.instance.getMessageText("column_title_key_end"))) return 11;
    if (title.equals(SkinManager.instance.getMessageText("column_title_key"))) return 12;
    if (title.equals(SkinManager.instance.getMessageText("column_title_song_comments"))) return 13;
    if (title.equals(SkinManager.instance.getMessageText("column_title_filename"))) return 14;
    if (title.equals(SkinManager.instance.getMessageText("column_title_analog"))) return 15;
    if (title.equals(SkinManager.instance.getMessageText("column_title_digital"))) return 16;
    if (title.equals(SkinManager.instance.getMessageText("column_title_disabled"))) return 17;
    if (title.equals(SkinManager.instance.getMessageText("column_title_bpm_shift"))) return 18;
    if (title.equals(SkinManager.instance.getMessageText("column_title_key_lock"))) return 19;
    if (title.equals(SkinManager.instance.getMessageText("column_title_num_mixouts"))) return 20;
    if (title.equals(SkinManager.instance.getMessageText("column_title_song_id_with_info"))) return 21;
    if (title.equals(SkinManager.instance.getMessageText("column_title_rank"))) return 22;
    if (title.equals(SkinManager.instance.getMessageText("column_title_num_addons"))) return 23;
    if (title.equals(SkinManager.instance.getMessageText("column_title_addon"))) return 24;
    if (title.equals(SkinManager.instance.getMessageText("column_title_bpm_diff"))) return 25;
    if (title.equals(SkinManager.instance.getMessageText("column_title_key_relation"))) return 26;
    if (title.equals(SkinManager.instance.getMessageText("column_title_remix"))) return 27;
    if (title.equals(OptionsUI.instance.customfieldtext1.getText())) return 28;
    if (title.equals(OptionsUI.instance.customfieldtext2.getText())) return 29;
    if (title.equals(OptionsUI.instance.customfieldtext3.getText())) return 30;
    if (title.equals(OptionsUI.instance.customfieldtext4.getText())) return 31;
    if (title.equals(SkinManager.instance.getMessageText("column_title_short_id"))) return 32;
    if (title.equals(SkinManager.instance.getMessageText("column_title_short_id_with_info"))) return 33;
    if (title.equals(SkinManager.instance.getMessageText("column_title_style_similarity"))) return 34;
    if (title.equals(SkinManager.instance.getMessageText("column_title_key_code"))) return 35;
    if (title.equals(SkinManager.instance.getMessageText("column_title_color_similarity"))) return 36;
    if (title.equals(SkinManager.instance.getMessageText("column_title_date_added"))) return 37;
    if (title.equals(SkinManager.instance.getMessageText("column_title_artist_similarity"))) return 38;
    if (title.equals(SkinManager.instance.getMessageText("column_title_mixout_comments"))) return 39;
    if (title.equals(SkinManager.instance.getMessageText("column_title_num_plays"))) return 40;
    if (title.equals(SkinManager.instance.getMessageText("column_title_key_accuracy"))) return 41;
    if (title.equals(SkinManager.instance.getMessageText("column_title_bpm_accuracy"))) return 42;    
    if (title.equals(SkinManager.instance.getMessageText("column_title_styles"))) return 43;    
    if (title.equals(SkinManager.instance.getMessageText("column_title_has_album_cover"))) return 44;    
    if (title.equals(SkinManager.instance.getMessageText("column_title_last_modified"))) return 45;    
    if (title.equals(SkinManager.instance.getMessageText("column_title_rating"))) return 46;    
    if (title.equals(SkinManager.instance.getMessageText("column_title_actual_key"))) return 47;    
    if (title.equals(SkinManager.instance.getMessageText("column_title_pitch_shift"))) return 48;    
    if (title.equals(SkinManager.instance.getMessageText("column_title_actual_key_code"))) return 49;    
    if (title.equals(SkinManager.instance.getMessageText("column_title_beat_intensity"))) return 50;    
    if (title.equals(SkinManager.instance.getMessageText("column_title_replay_gain"))) return 51;
    if (title.equals(SkinManager.instance.getMessageText("column_title_album_cover"))) return 52;
    return -1;
  }
  public static String getKeyword(int cindex) {
    if (cindex == 0) return new String(SkinManager.instance.getMessageText("column_title_song_id"));
    if (cindex == 1) return new String(SkinManager.instance.getMessageText("column_title_artist"));
    if (cindex == 2) return new String(SkinManager.instance.getMessageText("column_title_album"));
    if (cindex == 3) return new String(SkinManager.instance.getMessageText("column_title_track"));
    if (cindex == 4) return new String(SkinManager.instance.getMessageText("column_title_title"));
    if (cindex == 5) return new String(SkinManager.instance.getMessageText("column_title_time"));
    if (cindex == 6) return new String(SkinManager.instance.getMessageText("column_title_time_signature"));
    if (cindex == 7) return new String(SkinManager.instance.getMessageText("column_title_bpm_start"));
    if (cindex == 8) return new String(SkinManager.instance.getMessageText("column_title_bpm_end"));
    if (cindex == 9) return new String(SkinManager.instance.getMessageText("column_title_bpm"));
    if (cindex == 10) return new String(SkinManager.instance.getMessageText("column_title_key_start"));
    if (cindex == 11) return new String(SkinManager.instance.getMessageText("column_title_key_end"));
    if (cindex == 12) return new String(SkinManager.instance.getMessageText("column_title_key"));
    if (cindex == 13) return new String(SkinManager.instance.getMessageText("column_title_song_comments"));
    if (cindex == 14) return new String(SkinManager.instance.getMessageText("column_title_filename"));
    if (cindex == 15) return new String(SkinManager.instance.getMessageText("column_title_analog"));
    if (cindex == 16) return new String(SkinManager.instance.getMessageText("column_title_digital"));
    if (cindex == 17) return new String(SkinManager.instance.getMessageText("column_title_disabled"));
    if (cindex == 18) return new String(SkinManager.instance.getMessageText("column_title_bpm_shift"));
    if (cindex == 19) return new String(SkinManager.instance.getMessageText("column_title_key_lock"));
    if (cindex == 20) return new String(SkinManager.instance.getMessageText("column_title_num_mixouts"));
    if (cindex == 21) return new String(SkinManager.instance.getMessageText("column_title_song_id_with_info"));
    if (cindex == 22) return new String(SkinManager.instance.getMessageText("column_title_rank"));
    if (cindex == 23) return new String(SkinManager.instance.getMessageText("column_title_num_addons"));
    if (cindex == 24) return new String(SkinManager.instance.getMessageText("column_title_addon"));
    if (cindex == 25) return new String(SkinManager.instance.getMessageText("column_title_bpm_diff"));
    if (cindex == 26) return new String(SkinManager.instance.getMessageText("column_title_key_relation"));
    if (cindex == 27) return new String(SkinManager.instance.getMessageText("column_title_remix"));
    if (cindex == 28) return new String(OptionsUI.instance.customfieldtext1.getText());
    if (cindex == 29) return new String(OptionsUI.instance.customfieldtext2.getText());
    if (cindex == 30) return new String(OptionsUI.instance.customfieldtext3.getText());
    if (cindex == 31) return new String(OptionsUI.instance.customfieldtext4.getText());
    if (cindex == 32) return new String(SkinManager.instance.getMessageText("column_title_short_id"));
    if (cindex == 33) return new String(SkinManager.instance.getMessageText("column_title_short_id_with_info"));
    if (cindex == 34) return new String(SkinManager.instance.getMessageText("column_title_style_similarity"));
    if (cindex == 35) return new String(SkinManager.instance.getMessageText("column_title_key_code"));
    if (cindex == 36) return new String(SkinManager.instance.getMessageText("column_title_color_similarity"));
    if (cindex == 37) return new String(SkinManager.instance.getMessageText("column_title_date_added"));
    if (cindex == 38) return new String(SkinManager.instance.getMessageText("column_title_artist_similarity"));
    if (cindex == 39) return new String(SkinManager.instance.getMessageText("column_title_mixout_comments"));
    if (cindex == 40) return new String(SkinManager.instance.getMessageText("column_title_num_plays"));
    if (cindex == 41) return new String(SkinManager.instance.getMessageText("column_title_key_accuracy"));
    if (cindex == 42) return new String(SkinManager.instance.getMessageText("column_title_bpm_accuracy"));
    if (cindex == 43) return new String(SkinManager.instance.getMessageText("column_title_styles"));
    if (cindex == 44)return new String(SkinManager.instance.getMessageText("column_title_has_album_cover"));               
    if (cindex == 45)return new String(SkinManager.instance.getMessageText("column_title_last_modified"));     
    if (cindex == 46) return new String(SkinManager.instance.getMessageText("column_title_rating"));
    if (cindex == 47)return new String(SkinManager.instance.getMessageText("column_title_actual_key"));     
    if (cindex == 48) return new String(SkinManager.instance.getMessageText("column_title_pitch_shift"));
    if (cindex == 49) return new String(SkinManager.instance.getMessageText("column_title_actual_key_code"));
    if (cindex == 50) return new String(SkinManager.instance.getMessageText("column_title_beat_intensity"));
    if (cindex == 51) return new String(SkinManager.instance.getMessageText("column_title_replay_gain"));
    if (cindex == 52) return new String(SkinManager.instance.getMessageText("column_title_album_cover"));
    return new String("invalid column code");
  }
  
  public int num_columns;
  public int[] columnindex = new int[0];
  private int[] preferredwidth = new int[0];
  public String[] columntitles = new String[0];
  public int primary_sort_column = -1;
  public boolean primary_sort_ascending = true;
  public int secondary_sort_column = -1;
  public boolean secondary_sort_ascending = true;
  public int tertiary_sort_column = -1;
  public boolean tertiary_sort_ascending = true;

  public void setPreferredWidth(int[] val) { preferredwidth = val; }
  public void setPreferredWidth(int index, int value) {
      preferredwidth[index] = value;
      preferredWidths[columnindex[index]] = value;
  }
  public int getPreferredWidth(int index) { return preferredwidth[index]; }
  
  public boolean containsColumnType(int type) {
      if (columnindex != null) {
          for (int i = 0; i < columnindex.length; ++i) if (columnindex[i] == type) return true;
      }
      return false;
  }

  public static int COLUMN_SONGID = 0;
  public static int COLUMN_ARTIST = 1;
  public static int COLUMN_ALBUM = 2;
  public static int COLUMN_TRACK = 3;
  public static int COLUMN_TITLE = 4;
  public static int COLUMN_TIME = 5;
  public static int COLUMN_TIMESIG = 6;
  public static int COLUMN_BPMSTART = 7;
  public static int COLUMN_BPMEND = 8;
  public static int COLUMN_BPM = 9;
  public static int COLUMN_KEYSTART = 10;
  public static int COLUMN_KEYEND = 11;
  public static int COLUMN_KEY = 12;
  public static int COLUMN_SONGCOMMENTS = 13;
  public static int COLUMN_FILENAME = 14;
  public static int COLUMN_ANALOG = 15;
  public static int COLUMN_DIGITAL = 16;
  public static int COLUMN_DISABLED = 17;
  public static int COLUMN_BPMSHIFT = 18;
  public static int COLUMN_KEYLOCK = 19;
  public static int COLUMN_NUMMIXOUTS = 20;
  public static int COLUMN_SONGIDWINFO = 21;
  public static int COLUMN_MIXOUT_RANK = 22;
  public static int COLUMN_NUM_ADDONS = 23;
  public static int COLUMN_MIXOUT_ADDON = 24;
  public static int COLUMN_BPMDIFF = 25;
  public static int COLUMN_KEYRELATION = 26;
  public static int COLUMN_REMIX = 27;
  public static int COLUMN_USER1 = 28;
  public static int COLUMN_USER2 = 29;
  public static int COLUMN_USER3 = 30;
  public static int COLUMN_USER4 = 31;
  public static int COLUMN_SHORTID = 32;
  public static int COLUMN_SHORTIDWINFO = 33;
  public static int COLUMN_STYLESIMILARITY = 34;
  public static int COLUMN_KEYCODE = 35;
  public static int COLUMN_COLORSIMILARITY = 36;
  public static int COLUMN_DATEADDED = 37;
  public static int COLUMN_ARTISTSIMILARITY = 38;
  public static int COLUMN_MIXOUT_COMMENTS = 39;
  public static int COLUMN_NUM_PLAYS = 40;
  public static int COLUMN_KEYACCURACY = 41;
  public static int COLUMN_BPMACCURACY = 42;
  public static int COLUMN_STYLES = 43;
  public static int COLUMN_HAS_ALBUM_COVER = 44;
  public static int COLUMN_LAST_MODIFIED = 45;
  public static int COLUMN_RATING = 46;
  public static int COLUMN_ACTUAL_KEY = 47;
  public static int COLUMN_PITCH_SHIFT = 48;
  public static int COLUMN_ACTUAL_KEY_CODE = 49;
  public static int COLUMN_BEAT_INTENSITY = 50;
  public static int COLUMN_REPLAY_GAIN = 51;
  public static int COLUMN_ALBUM_COVER = 52;
  
};
